
import javax.swing.JFrame;
import javax.swing.JOptionPane;
//import quiz.addQuestion;
//import quiz.deleteQuestion;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author MyPC
 */
public class adminHome extends javax.swing.JFrame {

    /**
     * Creates new form adminHome
     */
    public adminHome() {
        initComponents();
        this.setLocationRelativeTo(null);
//        jLabel_add.setText("Thêm câu hỏi");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel_add = new javax.swing.JLabel();
        jLabel_update = new javax.swing.JLabel();
        jLabel_all_question = new javax.swing.JLabel();
        jLabel_logout = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jLabel_delete = new javax.swing.JLabel();
        jLabel_all_user = new javax.swing.JLabel();
        jSeparator5 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1200, 600));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 0, 102));

        jLabel_add.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel_add.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_add.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_add.setText("Thêm câu hỏi");
        jLabel_add.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_addMouseClicked(evt);
            }
        });

        jLabel_update.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel_update.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_update.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_update.setText("Chỉnh sửa câu hỏi");
        jLabel_update.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_updateMouseClicked(evt);
            }
        });

        jLabel_all_question.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel_all_question.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_all_question.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_all_question.setText("Xem tất cả câu hỏi");
        jLabel_all_question.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_all_questionMouseClicked(evt);
            }
        });

        jLabel_logout.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel_logout.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_logout.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_logout.setText("Đăng xuất");
        jLabel_logout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_logoutMouseClicked(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("<html>Quản lý <br>Hệ thống <br>");
        jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));

        jLabel_delete.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel_delete.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_delete.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_delete.setText("Xóa câu hỏi");
        jLabel_delete.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_deleteMouseClicked(evt);
            }
        });

        jLabel_all_user.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel_all_user.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_all_user.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_all_user.setText("Xem tất cả kết quả");
        jLabel_all_user.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_all_userMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator4)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jSeparator5)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                    .addContainerGap()
                                    .addComponent(jSeparator3, javax.swing.GroupLayout.DEFAULT_SIZE, 215, Short.MAX_VALUE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                    .addGap(25, 25, 25)
                                    .addComponent(jLabel_update))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                    .addContainerGap()
                                    .addComponent(jLabel_add, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addContainerGap()
                                    .addComponent(jSeparator1))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addContainerGap()
                                    .addComponent(jSeparator2))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                    .addGap(28, 28, 28)
                                    .addComponent(jLabel_all_question)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(29, 29, 29)
                                .addComponent(jLabel_delete))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(31, 31, 31)
                                .addComponent(jLabel_logout)))
                        .addGap(0, 13, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel_all_user)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addComponent(jLabel_add, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel_update)
                .addGap(18, 18, 18)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel_all_question)
                .addGap(22, 22, 22)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel_delete)
                .addGap(18, 18, 18)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19)
                .addComponent(jLabel_all_user)
                .addGap(18, 18, 18)
                .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel_logout)
                .addContainerGap(244, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 240, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel_addMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_addMouseClicked
        // TODO add your handling code here:
//        if (open == 0) {
            new addQuestion().setVisible(true);
            this.setVisible(false);
//            open= 1;
//        } else {
//            JFrame frame = new JFrame();
//            frame.setAlwaysOnTop(true);
//            JOptionPane.showMessageDialog(frame, "One form was already opened!");
//        }
    }//GEN-LAST:event_jLabel_addMouseClicked

    private void jLabel_updateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_updateMouseClicked
        // TODO add your handling code here:
//        if (open == 0) {
            new updateQuestion().setVisible(true);
                        this.setVisible(false);

//            open= 1;
//        } else {
//            JFrame frame = new JFrame();
//            frame.setAlwaysOnTop(true);
//            JOptionPane.showMessageDialog(frame, "One form was already opened!");
//        }
    }//GEN-LAST:event_jLabel_updateMouseClicked

    private void jLabel_all_questionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_all_questionMouseClicked
        // TODO add your handling code here:
//        if (open == 0) {
            new all_question().setVisible(true);
                        this.setVisible(false);

//            open= 1;
//        } else {
//            JFrame frame = new JFrame();
//            frame.setAlwaysOnTop(true);
//            JOptionPane.showMessageDialog(frame, "One form was already opened!");
//        }
    }//GEN-LAST:event_jLabel_all_questionMouseClicked

    private void jLabel_deleteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_deleteMouseClicked
        // TODO add your handling code here:
//        if (open == 0) {
            new deleteQuestion().setVisible(true);
                        this.setVisible(false);

//            open= 1;
//        } else {
//            JFrame frame = new JFrame();
//            frame.setAlwaysOnTop(true);
//            JOptionPane.showMessageDialog(frame, "One form was already opened!");
//        }
    }//GEN-LAST:event_jLabel_deleteMouseClicked

    private void jLabel_logoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_logoutMouseClicked
        // TODO add your handling code here:
        JFrame frame = new JFrame();
        frame.setAlwaysOnTop(true);
        int a = JOptionPane.showConfirmDialog(frame, "Do you really want to log out?", "Select", JOptionPane.YES_NO_OPTION);
        if(a == 0){
            setVisible(false);
            new LoginForm().setVisible(true);
        }
    }//GEN-LAST:event_jLabel_logoutMouseClicked

    private void jLabel_all_userMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_all_userMouseClicked
        // TODO add your handling code here:
        new allResult().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jLabel_all_userMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(adminHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(adminHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(adminHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(adminHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new adminHome().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel_add;
    private javax.swing.JLabel jLabel_all_question;
    private javax.swing.JLabel jLabel_all_user;
    private javax.swing.JLabel jLabel_delete;
    private javax.swing.JLabel jLabel_logout;
    private javax.swing.JLabel jLabel_update;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    // End of variables declaration//GEN-END:variables
}
