/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
//package quiz;

import java.awt.Image;
import java.awt.Toolkit;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.Connection;
import java.sql.SQLException;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Collections;
import java.util.Date;
import java.util.List;
import java.util.Random;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.Timer;

/**
 *
 * @author ASUS
 */
public class question extends javax.swing.JFrame {
     public String questionId = "1";
    public int questionNo = 1, totalQuestion = 0;
    public String answer;
    public int min = 0, sec = 0, marks = 0;
    public Timer time;//dùng để hiển thị tính giờ làm bài
    public ArrayList<String> selectedQuestions = new ArrayList<String>();
    String contentOfQuestion = "";
    String nameuser="";
    String uname="";
    /**
     * Creates new form question
     */
    public question() {
        initComponents();
        this.setLocationRelativeTo(null);
    }
    
    public question(String u_name) {
        initComponents();
        this.setLocationRelativeTo(null);

//        this.setSize(1090, 500);
//        jLabel_rollNo.setText(rollNo);
//        byte[] image = null;
              
        //date
//        SimpleDateFormat sdf = new SimpleDateFormat("dd-MM-yyyy");
//        Date date = new Date();
//        jLabel_time.setText(sdf.format(date));
        
        //first question and student details
        try {
//            Connection con = ConnectionProvider.getCon();
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost/quiz", "root", "032962672203296");
            Statement st = con.createStatement(ResultSet.TYPE_SCROLL_SENSITIVE, 
                        ResultSet.CONCUR_UPDATABLE);//Notice, this line may be throw sql exception 
            ResultSet rs = st.executeQuery("select * from user" + " where u_uname = '"+u_name+"'");
            while(rs.next()){
                jLabel_name.setText(rs.getString(2));
                nameuser = rs.getString(2);
                uname= rs.getString(1);
            }
            
            //Lấy số tổng số câu hỏi có trong CSDL
            ResultSet rs1 = st.executeQuery("select count(*) from question");
            while(rs1.next()){
                totalQuestion = rs1.getInt(1);
            }
            
            //Hiển thị câu hỏi đầu tiên
            int questionId1 = 1;
            questionId = String.valueOf(questionId1);
            selectedQuestions.add(questionId);
            
            ResultSet rs2 = st.executeQuery("select * from question where id = '"+questionId+"'");
            while(rs2.next()){
                jLabel_question_number.setText(String.valueOf(questionNo));
                contentOfQuestion = rs2.getString(2);
//                if(contentOfQuestion.length() >= 10){
//                    contentOfQuestion = "<html><p style=\"font-size:15px;width:750px;\"><b>" 
//                            + contentOfQuestion + "</b><br></p></html>";
//                }
                jLabel_content_question.setText(contentOfQuestion);
                jRadioButton_opt1.setText(rs2.getString(3));
                jRadioButton_opt2.setText(rs2.getString(4));
                jRadioButton_opt3.setText(rs2.getString(5));
                jRadioButton_opt4.setText(rs2.getString(6));
                answer = rs2.getString(7);
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e);
        }
        
        
        time = new Timer(1000, (ActionEvent e) -> {
            jLabel_sec.setText(String.valueOf(sec));
            jLabel_min.setText(String.valueOf(min));
            
            if (sec==60) {
                sec = 0;
                min++;
                if(min == 10){
                    time.stop();
                        answerCheck();
//                        new Submitted(marks,nameuser).setVisible(true);
                }
            }
            sec++;
        });
        time.start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel2 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel_Total_question = new javax.swing.JLabel();
        jLabel_marks = new javax.swing.JLabel();
        jLabel_name = new javax.swing.JLabel();
        jLabel_avatar = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel_question_number = new javax.swing.JLabel();
        jLabel_content_question = new javax.swing.JLabel();
        jRadioButton_opt1 = new javax.swing.JRadioButton();
        jRadioButton_opt2 = new javax.swing.JRadioButton();
        jRadioButton_opt3 = new javax.swing.JRadioButton();
        jRadioButton_opt4 = new javax.swing.JRadioButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel_min = new javax.swing.JLabel();
        jLabel = new javax.swing.JLabel();
        jLabel_sec = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jButton_next = new javax.swing.JButton();
        jButton_submit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1200, 600));
        setPreferredSize(new java.awt.Dimension(1200, 600));
        setSize(new java.awt.Dimension(1200, 500));

        jPanel2.setBackground(new java.awt.Color(0, 0, 51));
        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));
        jPanel2.setForeground(new java.awt.Color(255, 255, 255));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Tổng Số Câu Hỏi:");

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Điểm:");

        jLabel_Total_question.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel_Total_question.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_Total_question.setText("10");

        jLabel_marks.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        jLabel_marks.setForeground(new java.awt.Color(255, 0, 0));
        jLabel_marks.setText("00");

        jLabel_name.setFont(new java.awt.Font("Comic Sans MS", 1, 28)); // NOI18N
        jLabel_name.setForeground(new java.awt.Color(0, 255, 0));
        jLabel_name.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_name.setText("Henry");

        jLabel_avatar.setIcon(new javax.swing.ImageIcon("C:\\Users\\ASUS\\Documents\\NetbeanProjects\\QUIZ\\QUIZ\\src\\avatar.png")); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel_Total_question)
                        .addContainerGap(12, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel_marks)
                        .addGap(16, 16, 16))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel_avatar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel_name)
                        .addContainerGap())))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel_name)
                    .addComponent(jLabel_avatar))
                .addGap(77, 77, 77)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(jLabel_Total_question))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(jLabel_marks))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jLabel_question_number.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel_question_number.setText("00");

        jLabel_content_question.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel_content_question.setText("Question demo?");

        buttonGroup1.add(jRadioButton_opt1);
        jRadioButton_opt1.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jRadioButton_opt1.setText("jRadioButton1");
        jRadioButton_opt1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton_opt1ActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButton_opt2);
        jRadioButton_opt2.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jRadioButton_opt2.setText("jRadioButton2");
        jRadioButton_opt2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton_opt2ActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButton_opt3);
        jRadioButton_opt3.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jRadioButton_opt3.setText("jRadioButton3");
        jRadioButton_opt3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton_opt3ActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButton_opt4);
        jRadioButton_opt4.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jRadioButton_opt4.setText("jRadioButton4");
        jRadioButton_opt4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton_opt4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel_question_number)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel_content_question)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jRadioButton_opt2)
                            .addComponent(jRadioButton_opt1)
                            .addComponent(jRadioButton_opt4)
                            .addComponent(jRadioButton_opt3))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_content_question)
                    .addComponent(jLabel_question_number))
                .addGap(26, 26, 26)
                .addComponent(jRadioButton_opt1)
                .addGap(18, 18, 18)
                .addComponent(jRadioButton_opt2)
                .addGap(18, 18, 18)
                .addComponent(jRadioButton_opt4)
                .addGap(18, 18, 18)
                .addComponent(jRadioButton_opt3)
                .addContainerGap(36, Short.MAX_VALUE))
        );

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setFont(new java.awt.Font("Algerian", 1, 60)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 255));
        jLabel2.setText("trac nghiem");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 0, 0));
        jLabel6.setText("Thời Gian:");

        jLabel_min.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel_min.setForeground(new java.awt.Color(255, 0, 0));
        jLabel_min.setText("00");

        jLabel.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel.setForeground(new java.awt.Color(255, 0, 0));
        jLabel.setText(":");

        jLabel_sec.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel_sec.setForeground(new java.awt.Color(255, 0, 0));
        jLabel_sec.setText("00");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 0, 0));
        jLabel5.setText("Tổng Thời Gian:");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 0, 0));
        jLabel7.setText("10 Phút");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 305, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel6)
                    .addComponent(jLabel5))
                .addGap(42, 42, 42)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel_min)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel_sec)))
                .addGap(111, 111, 111))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(47, 47, 47))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel_sec)
                            .addComponent(jLabel_min)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel6)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jButton_next.setBackground(new java.awt.Color(255, 153, 0));
        jButton_next.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton_next.setForeground(new java.awt.Color(255, 255, 255));
        jButton_next.setText("Next");
        jButton_next.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_nextActionPerformed(evt);
            }
        });

        jButton_submit.setBackground(new java.awt.Color(255, 153, 0));
        jButton_submit.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton_submit.setForeground(new java.awt.Color(255, 255, 255));
        jButton_submit.setText("Submit");
        jButton_submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_submitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(150, 150, 150)
                        .addComponent(jButton_submit, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton_next, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(174, 174, 174))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(51, 51, 51)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton_next, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton_submit, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(32, 32, 32)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jRadioButton_opt1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton_opt1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton_opt1ActionPerformed

    private void jRadioButton_opt2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton_opt2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton_opt2ActionPerformed

    private void jRadioButton_opt3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton_opt3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton_opt3ActionPerformed

    private void jRadioButton_opt4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton_opt4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton_opt4ActionPerformed

    private void jButton_submitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_submitActionPerformed
        this.setVisible(false);
        new Submitted(marks,uname).setVisible(true);
    }//GEN-LAST:event_jButton_submitActionPerformed

    private void jButton_nextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_nextActionPerformed
        // TODO add your handling code here:
        answerCheck();
        question();
    }//GEN-LAST:event_jButton_nextActionPerformed

    
     public void answerCheck(){
        String studentAnswer = "";
//        System.out.print(answer);
        if(jRadioButton_opt1.isSelected()){
            studentAnswer = "A";
        }
        else if(jRadioButton_opt2.isSelected()){
            studentAnswer = "B";
        }
        else if(jRadioButton_opt3.isSelected()){
            studentAnswer = "C";
        }
        else if(jRadioButton_opt4.isSelected()){
            studentAnswer = "D";
        }
        
        try{
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost/quiz", "root", "032962672203296");
            String decisionQuery = "INSERT INTO submit (username, Cau, DapAn) VALUES (?,?,?)";
            PreparedStatement pst = con.prepareStatement(decisionQuery);
            pst.setString(1,uname );
            pst.setInt(2,Integer.parseInt(questionId));
            pst.setString(3, studentAnswer);
            pst.executeUpdate();
        }
        catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
        if(studentAnswer.equalsIgnoreCase(answer)){
            marks = marks + 1;
            String marks1 = String.valueOf(marks);
            jLabel_marks.setText(marks1);
            
        }
        
        
        //question number change and display next question
        questionNo += 1;
        Random rd = new Random();
        int questionId1 = rd.nextInt(totalQuestion);
        questionId = String.valueOf(questionId1);
        while(selectedQuestions.indexOf(questionId) != -1 || questionId1==0){
            questionId1 = rd.nextInt(totalQuestion);
            questionId = String.valueOf(questionId1);
        }
        
        selectedQuestions.add(questionId);
        System.out.print(selectedQuestions);        
        //clear JRadioButton
//        jRadioButton_opt1.setSelected(false);
//        jRadioButton_opt2.setSelected(false);
//        jRadioButton_opt3.setSelected(false);
//        jRadioButton_opt4.setSelected(false);
        buttonGroup1.clearSelection();

        //Last question hide next button
        if(questionNo == 8){
            jButton_next.setVisible(false);
        }
    }
     
      public void question(){
        try { 
//            Connection con = ConnectionProvider.getCon();
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost/quiz", "root", "032962672203296");
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery("select * from question where id = '"+questionId+"'");
            jLabel_question_number.setText(String.valueOf(questionNo));
            while(rs.next()){
                contentOfQuestion = rs.getString(2);
//                if(contentOfQuestion.length() >= 10){
//                    contentOfQuestion = "<html><p style=\"font-size:15px;width:750px;\"><b>" 
//                            + contentOfQuestion + "</b></p><br></html>";
//                }
                jLabel_content_question.setText(contentOfQuestion);
                
                //Lưu 4 lựa chọn của mỗi cầu hỏi vào 1 danh sách và hiển thị chúng ra màn hình
                List<String> stringListQuestions = new ArrayList<String>();
                stringListQuestions.add(rs.getString(3));
                stringListQuestions.add(rs.getString(4));
                stringListQuestions.add(rs.getString(5));
                stringListQuestions.add(rs.getString(6));
//		Collections.shuffle(stringListQuestions);

                jRadioButton_opt1.setText(stringListQuestions.get(0));
                jRadioButton_opt2.setText(stringListQuestions.get(1));
                jRadioButton_opt3.setText(stringListQuestions.get(2));
                jRadioButton_opt4.setText(stringListQuestions.get(3));
                answer = rs.getString(7);
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }
     
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(question.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(question.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(question.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(question.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new question().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton_next;
    private javax.swing.JButton jButton_submit;
    private javax.swing.JLabel jLabel;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel_Total_question;
    private javax.swing.JLabel jLabel_avatar;
    private javax.swing.JLabel jLabel_content_question;
    private javax.swing.JLabel jLabel_marks;
    private javax.swing.JLabel jLabel_min;
    private javax.swing.JLabel jLabel_name;
    private javax.swing.JLabel jLabel_question_number;
    private javax.swing.JLabel jLabel_sec;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JRadioButton jRadioButton_opt1;
    private javax.swing.JRadioButton jRadioButton_opt2;
    private javax.swing.JRadioButton jRadioButton_opt3;
    private javax.swing.JRadioButton jRadioButton_opt4;
    // End of variables declaration//GEN-END:variables
}
