import quiz.src.*;
import java.awt.Font;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.PreparedStatement;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author MyPC
 */
public class Submitted extends javax.swing.JFrame {
    String name_u;
    /**
     * Creates new form successfullySubmited
     */
//     String marks , String rollNo, String name
    public Submitted() {
        initComponents();  
        this.setLocationRelativeTo(null);
    }
    public Submitted(int marks , String name) {
        initComponents();
        this.setLocationRelativeTo(null);
        String marks1 = "Điểm đạt được: " + marks;
        jLabel2.setText(marks1);
        try{
         Connection con = DriverManager.getConnection("jdbc:mysql://localhost/quiz", "root", "032962672203296");
         PreparedStatement ps = con.prepareStatement("insert into marks (username,mark) value (?,?)");
         ps.setString(1, name);
         ps.setInt(2, marks);
         ps.executeUpdate();
         name_u = name;
        }
        catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
        if(marks >= 8){
            ImageIcon icon = new ImageIcon(getClass().getResource("/ezgif.com-gif-maker (1).gif"));
            jLabel_low_result.setIcon(icon);
            jLabel_name1.setText("<html><p style=\"text-align: center;\">Chúc Mừng!</p></html>");
        }
        else{
            ImageIcon icon = new ImageIcon(getClass().getResource("/sadness.png"));
            jLabel_low_result.setIcon(icon);
            jLabel_name1.setText("");
//            jLabel_name1.setText("<html><p style=\"text-align: center;\">" + name + ", Bạn Cần Luyện Tập Nhiều Hơn! </p></html>");
        }
    }
    /**
     * Creates new form Submitted
     */
//    public Submitted() {
//        initComponents();
//    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel_low_result = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel_name1 = new javax.swing.JLabel();
        jButton_logout1 = new javax.swing.JButton();
        jButton_chiTietkq = new javax.swing.JButton();
        jButton_restart = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1200, 600));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));
        jPanel1.setMinimumSize(new java.awt.Dimension(1200, 600));
        jPanel1.setPreferredSize(new java.awt.Dimension(1200, 600));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 60)); // NOI18N
        jLabel2.setText("Điểm đạt được: 10");

        jLabel_name1.setFont(new java.awt.Font("Tahoma", 1, 50)); // NOI18N
        jLabel_name1.setText("Cập nhật thành công");

        jButton_logout1.setBackground(new java.awt.Color(0, 153, 51));
        jButton_logout1.setFont(new java.awt.Font("Tahoma", 1, 40)); // NOI18N
        jButton_logout1.setForeground(new java.awt.Color(255, 255, 255));
        jButton_logout1.setText("LOG OUT");
        jButton_logout1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_logout1ActionPerformed(evt);
            }
        });

        jButton_chiTietkq.setBackground(new java.awt.Color(0, 153, 51));
        jButton_chiTietkq.setFont(new java.awt.Font("Tahoma", 1, 40)); // NOI18N
        jButton_chiTietkq.setForeground(new java.awt.Color(255, 255, 255));
        jButton_chiTietkq.setText("Chi Tiết Kết Quả");
        jButton_chiTietkq.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_chiTietkqActionPerformed(evt);
            }
        });

        jButton_restart.setBackground(new java.awt.Color(0, 153, 51));
        jButton_restart.setFont(new java.awt.Font("Tahoma", 1, 40)); // NOI18N
        jButton_restart.setForeground(new java.awt.Color(255, 255, 255));
        jButton_restart.setText("RESTART");
        jButton_restart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_restartActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(330, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel_low_result, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(450, 450, 450))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(312, 312, 312))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel_name1)
                        .addGap(322, 322, 322))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addComponent(jButton_restart)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton_chiTietkq)
                .addGap(100, 100, 100)
                .addComponent(jButton_logout1)
                .addGap(134, 134, 134))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel_low_result, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jLabel_name1)
                .addGap(41, 41, 41)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_logout1)
                    .addComponent(jButton_chiTietkq)
                    .addComponent(jButton_restart))
                .addContainerGap(120, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 600));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_logout1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_logout1ActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        new LoginForm().setVisible(true);
    }//GEN-LAST:event_jButton_logout1ActionPerformed

    private void jButton_restartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_restartActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        new question(name_u).setVisible(true);
        try{
            String restartQuery = "delete from submit";
            PreparedStatement ps = MyConnection.getConnection().prepareStatement(restartQuery);
                        ps.executeUpdate();

        }
         catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_jButton_restartActionPerformed

    private void jButton_chiTietkqActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_chiTietkqActionPerformed
        // TODO add your handling code here:
       ChiTietKq ct = new ChiTietKq();
        ct.setVisible(true);
        ct.pack();
        ct.setLocationRelativeTo(null);
        ct.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();

    }//GEN-LAST:event_jButton_chiTietkqActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Submitted.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Submitted.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Submitted.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Submitted.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Submitted().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_chiTietkq;
    private javax.swing.JButton jButton_logout1;
    private javax.swing.JButton jButton_restart;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel_low_result;
    private javax.swing.JLabel jLabel_name1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
