import java.awt.Font;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author MyPC
 */
public class Submitted extends javax.swing.JFrame {
     public String rollNo;
    /**
     * Creates new form successfullySubmited
     */
//     String marks , String rollNo, String name
      public Submitted() {
        initComponents();  
      }
    public Submitted(String marks , String rollNo, String name) {
        initComponents();
        String marks1 = "Marks Obtained: " + marks;
        jLabel2.setText(marks1);
        this.rollNo = rollNo;
        if(Integer.parseInt(marks) >= 8){
            ImageIcon icon = new ImageIcon(getClass().getResource("/ezgif.com-gif-maker (1).gif"));
            jLabel_high_result.setIcon(icon);
            jLabel_name1.setText("Congratulation!");
        }
        else{
            ImageIcon icon = new ImageIcon(getClass().getResource("/sadness.png"));
            jLabel_low_result.setIcon(icon);
            jLabel_name1.setText("<html>"+name + ", you need more <br>practice!</html>");
        }
    }
    /**
     * Creates new form Submitted
     */
//    public Submitted() {
//        initComponents();
//    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel_name1 = new javax.swing.JLabel();
        jButton_restart1 = new javax.swing.JButton();
        jButton_logout1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel_low_result = new javax.swing.JLabel();
        jLabel_high_result = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 60)); // NOI18N
        jLabel2.setText("Marks Obtained: 10");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 280, -1, -1));

        jLabel_name1.setFont(new java.awt.Font("Tahoma", 1, 60)); // NOI18N
        jLabel_name1.setText("Successfully Updated");
        getContentPane().add(jLabel_name1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 370, -1, -1));

        jButton_restart1.setBackground(new java.awt.Color(0, 153, 51));
        jButton_restart1.setFont(new java.awt.Font("Tahoma", 1, 40)); // NOI18N
        jButton_restart1.setForeground(new java.awt.Color(255, 255, 255));
        jButton_restart1.setText("RESTART");
        jButton_restart1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_restart1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_restart1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 600, -1, -1));

        jButton_logout1.setBackground(new java.awt.Color(0, 153, 51));
        jButton_logout1.setFont(new java.awt.Font("Tahoma", 1, 40)); // NOI18N
        jButton_logout1.setForeground(new java.awt.Color(255, 255, 255));
        jButton_logout1.setText("LOG OUT");
        jButton_logout1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_logout1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_logout1, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 600, -1, -1));

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(74, 74, 74)
                .addComponent(jLabel_low_result, javax.swing.GroupLayout.PREFERRED_SIZE, 1049, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel_high_result, javax.swing.GroupLayout.PREFERRED_SIZE, 581, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(343, 343, 343))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(296, 296, 296)
                .addComponent(jLabel_high_result, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel_low_result, javax.swing.GroupLayout.PREFERRED_SIZE, 512, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 258, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-50, 0, 1370, 770));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_restart1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_restart1ActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        //        new quizExamStudent(rollNo).setVisible(true);
    }//GEN-LAST:event_jButton_restart1ActionPerformed

    private void jButton_logout1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_logout1ActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        new LoginForm().setVisible(true);
    }//GEN-LAST:event_jButton_logout1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Submitted.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Submitted.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Submitted.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Submitted.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Submitted().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_logout1;
    private javax.swing.JButton jButton_restart1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel_high_result;
    private javax.swing.JLabel jLabel_low_result;
    private javax.swing.JLabel jLabel_name1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
