/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package quiz;
//import "./MyConnection";
import com.mysql.cj.xdevapi.Warning;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Iterator;
import javax.swing.JOptionPane;
import javax.swing.JRadioButton;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
/**
 *
 * @author ASUS
 */
public class allques extends javax.swing.JFrame {
    Connection con = null;
    PreparedStatement pst = null;
    ResultSet rs;
//    ResultSet ResultSet;
    int num=0;
    int correct=0;
    String dan;
//    JTextField tfield = new JTextField();
    public allques() {
        initComponents();
        try{
            String showQuery = "select * from question where id = 1";
            con = DriverManager.getConnection("jdbc:mysql://localhost/quiz", "root", "032962672203296");
            pst = con.prepareStatement(showQuery);
            rs = pst.executeQuery();
            if(rs.next()){
                String show = "<html>";
                show += rs.getString("CauHoi") + "<br>";
                String daA = "<html>";
                daA += rs.getString("DaA") + "<br>";
                String daB = "<html>";
                daB += rs.getString("DaB") + "<br>"; 
                String daC = "<html>";
                daC += rs.getString("DaC") + "<br>"; 
                String daD = "<html>";
                daD += rs.getString("DaD") + "<br>";
                num += rs.getByte("id");
                jLabel1.setText(show);
                jLabel3.setText("Câu " + num);
                r1.setText(daA);
                r2.setText(daB); 
                r3.setText(daC);
                r4.setText(daD);
            }
        }
        catch (SQLException ex){
            JOptionPane.showMessageDialog(null, ex.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        r1 = new javax.swing.JRadioButton();
        r2 = new javax.swing.JRadioButton();
        r3 = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        r4 = new javax.swing.JRadioButton();
        Submit = new javax.swing.JButton();
        Previous = new javax.swing.JButton();
        Next = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(153, 153, 0));
        setForeground(java.awt.Color.yellow);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 204, 0));
        jLabel2.setText("Câu hỏi trắc nghiệm");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("Question");

        buttonGroup1.add(r1);
        r1.setText("jRadioButton1");
        r1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r1ActionPerformed(evt);
            }
        });

        buttonGroup1.add(r2);
        r2.setText("jRadioButton2");
        r2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r2ActionPerformed(evt);
            }
        });

        buttonGroup1.add(r3);
        r3.setText("jRadioButton3");
        r3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r3ActionPerformed(evt);
            }
        });

        jLabel3.setText("jLabel3");

        buttonGroup1.add(r4);
        r4.setText("jRadioButton4");
        r4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r4ActionPerformed(evt);
            }
        });

        Submit.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Submit.setText("Submit");
        Submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubmitActionPerformed(evt);
            }
        });

        Previous.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Previous.setText("Câu trước");
        Previous.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PreviousActionPerformed(evt);
            }
        });

        Next.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Next.setText("Câu tiếp theo");
        Next.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NextActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 392, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(Previous)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(Submit)
                                .addGap(90, 90, 90)
                                .addComponent(Next))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(r1, javax.swing.GroupLayout.DEFAULT_SIZE, 392, Short.MAX_VALUE)
                            .addComponent(r2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(r3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(r4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(68, 68, 68))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addComponent(r1)
                .addGap(12, 12, 12)
                .addComponent(r2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(r3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(r4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Submit)
                    .addComponent(Previous)
                    .addComponent(Next))
                .addGap(38, 38, 38))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void getSelectOptions(JRadioButton rbutton){
        
        
        if(rbutton.equals(r1)){
            dan = "A";
        } else if(rbutton.equals(r2)){
            dan = "B";
        }else if(rbutton.equals(r3)){
            dan = "C";
        }else {
            dan = "D";
        }
        String KetQua = null;
        try{
          String submitQuery = "INSERT INTO submit (Cau, DapAn) VALUES (?, ?)";
          con = DriverManager.getConnection("jdbc:mysql://localhost/quiz", "root", "032962672203296");
           pst = con.prepareStatement(submitQuery);
           pst.setInt(1, num);
           pst.setString(2, dan);
           pst.executeUpdate(); 
           String resultQuery= "SELECT * FROM question WHERE id='" + num + "'" ;
             pst = con.prepareStatement(resultQuery);
             rs = pst.executeQuery(); 
            if(rs.next()){
                if(rs.getString("DACX").equals(dan)){
//                    KetQua = "INSERT INTO submit (KetQua) VALUES true where id = '" + num + "'";
                      KetQua = "UPDATE submit SET KetQua = '1' WHERE Cau = '" + num + "'";
                      correct++;
                } else{
                    KetQua = "UPDATE submit SET KetQua = '0' WHERE Cau = '" + num + "'";
                }
            }
            pst = con.prepareStatement(KetQua);
            pst.executeUpdate();
        }
        catch (SQLException ex){
           JOptionPane.showMessageDialog(null, ex.getMessage()); 
        }
//            System.out.print(num);
//        enableRbuttons(false);
        
    }
    
    public void enableRbuttons(boolean yes_or_no)
    {
        r1.setEnabled(yes_or_no);
        r2.setEnabled(yes_or_no);
        r3.setEnabled(yes_or_no);
        r4.setEnabled(yes_or_no);
    }
    
    private void r1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r1ActionPerformed
        getSelectOptions(r1);
    }//GEN-LAST:event_r1ActionPerformed

    private void PreviousActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PreviousActionPerformed
          try{
            num -= 1;
            String showQuery = "select * from question where id = '" + num + "'";
//            String query = "SELECT givenanswer FROM questions WHERE question = '"+txtques.getText()+"'";
            con = DriverManager.getConnection("jdbc:mysql://localhost/quiz", "root", "032962672203296");
            pst = con.prepareStatement(showQuery);
            rs = pst.executeQuery();
            if(rs.next()){
                String show1 = "<html>";
                show1 += rs.getString("CauHoi") + "<br>";
                String dA = "<html>";
                dA += rs.getString("DaA") + "<br>";
                String dB = "<html>";
                dB += rs.getString("DaB") + "<br>"; 
                String dC = "<html>";
                dC += rs.getString("DaC") + "<br>"; 
                String dD = "<html>";
                dD += rs.getString("DaD") + "<br>";
                num = rs.getByte("id");
                jLabel1.setText(show1);
                jLabel3.setText("Câu " + num);
                r1.setText(dA);
                r2.setText(dB); 
                r3.setText(dC);
                r4.setText(dD);
            } else {
                JOptionPane.showMessageDialog(this, "Đây là câu hỏi đầu tiên");
            }
        }
        catch (SQLException ex){
            JOptionPane.showMessageDialog(null, ex.getMessage());
        } 
    }//GEN-LAST:event_PreviousActionPerformed

    private void NextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NextActionPerformed
            try{
            num += 1;
            String showQuery = "select * from question where id = '" + num + "'";
//            String query = "SELECT givenanswer FROM questions WHERE question = '"+txtques.getText()+"'";
            con = DriverManager.getConnection("jdbc:mysql://localhost/quiz", "root", "032962672203296");
            pst = con.prepareStatement(showQuery);
            rs = pst.executeQuery();
            if(rs.next()){
                String show1 = "<html>";
                show1 += rs.getString("CauHoi") + "<br>";
                String dA = "<html>";
                dA += rs.getString("DaA") + "<br>";
                String dB = "<html>";
                dB += rs.getString("DaB") + "<br>"; 
                String dC = "<html>";
                dC += rs.getString("DaC") + "<br>"; 
                String dD = "<html>";
                dD += rs.getString("DaD") + "<br>";
                num = rs.getByte("id");
                jLabel1.setText(show1);
                jLabel3.setText("Câu " + num);
                r1.setText(dA);
                r2.setText(dB); 
                r3.setText(dC);
                r4.setText(dD);
            } else {
                JOptionPane.showMessageDialog(this, "Đây là câu hỏi cuối cùng.");
            }
        }
        catch (SQLException ex){
            JOptionPane.showMessageDialog(null, ex.getMessage());
        } 
            
        enableRbuttons(true);
        buttonGroup1.clearSelection();
    }//GEN-LAST:event_NextActionPerformed

    private void SubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubmitActionPerformed
//     RegisterForm rgf = new RegisterForm();
        ReSult rs2 = new ReSult(correct);
        rs2.setVisible(true);
        rs2.pack();
        rs2.setLocationRelativeTo(null);
        rs2.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
        
    }//GEN-LAST:event_SubmitActionPerformed

    private void r2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r2ActionPerformed
        getSelectOptions(r2);
    }//GEN-LAST:event_r2ActionPerformed

    private void r3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r3ActionPerformed
        getSelectOptions(r3);
    }//GEN-LAST:event_r3ActionPerformed

    private void r4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r4ActionPerformed
        getSelectOptions(r4);
    }//GEN-LAST:event_r4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(allques.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(allques.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(allques.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(allques.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new allques().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Next;
    private javax.swing.JButton Previous;
    private javax.swing.JButton Submit;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton r1;
    private javax.swing.JRadioButton r2;
    private javax.swing.JRadioButton r3;
    private javax.swing.JRadioButton r4;
    // End of variables declaration//GEN-END:variables
}
